name: BuildCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.8.0
      - name: Compile all
        run: mill _.compile
      - name: Run all
        run: mill _.run 